- name: Retrieve all tags on an instance
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Retrieve all tags on an instance
      amazon.aws.ec2_tag_info:
        region: eu-west-1
        resource: i-06f7d930d51b4fc6a
      register: instance_tags