- name: Retrieve all tags on an instance
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: import vars
      include_vars: vars/vpc_setup

    - name: Retrieve all tags on an instance
      ec2_tag_info:
        region: "{{region}}"
        resource: i-06f7d930d51b4fc6a
      register: instance_tags