- name: set host to ip mapping in /etc/hosts file of all the instances in the stack
  hosts: all
  tasks:
    - name: import VPC setup variable
      include_vars: group_vars/hostsip

    - name: Update hosts file of all hosts
      blockinfile:
        path: /etc/hosts
        block: |
          {{web01_ip}} web01
          {{app01_ip}} app01
          {{rmq01_ip}} rmq01
          {{mc01_ip}} mc01
          {{db01_ip}} db01
